/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApiHealthChatRouteImport } from './routes/api/health-chat'
import { Route as ApiKakaoAlertRouteImport } from './routes/api/kakao-alert'
import { Route as ApiSpeechRouteImport } from './routes/api/speech'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as AuthenticatedCConversationIdRouteImport } from './routes/_authenticated/c.$conversationId'
import { Route as ApiPublicMcpRouteImport } from './routes/api/public/mcp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthChatRoute = ApiHealthChatRouteImport.update({
  id: '/api/health-chat',
  path: '/api/health-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKakaoAlertRoute = ApiKakaoAlertRouteImport.update({
  id: '/api/kakao-alert',
  path: '/api/kakao-alert',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpeechRoute = ApiSpeechRouteImport.update({
  id: '/api/speech',
  path: '/api/speech',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCConversationIdRoute =
  AuthenticatedCConversationIdRouteImport.update({
    id: '/c/$conversationId',
    path: '/c/$conversationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicMcpRoute = ApiPublicMcpRouteImport.update({
  id: '/api/public/mcp',
  path: '/api/public/mcp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/health-chat': typeof ApiHealthChatRoute
  '/api/kakao-alert': typeof ApiKakaoAlertRoute
  '/api/speech': typeof ApiSpeechRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/c/$conversationId': typeof AuthenticatedCConversationIdRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/health-chat': typeof ApiHealthChatRoute
  '/api/kakao-alert': typeof ApiKakaoAlertRoute
  '/api/speech': typeof ApiSpeechRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/c/$conversationId': typeof AuthenticatedCConversationIdRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/api/health-chat': typeof ApiHealthChatRoute
  '/api/kakao-alert': typeof ApiKakaoAlertRoute
  '/api/speech': typeof ApiSpeechRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/_authenticated/c/$conversationId': typeof AuthenticatedCConversationIdRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/api/health-chat'
    | '/api/kakao-alert'
    | '/api/speech'
    | '/api/transcribe'
    | '/c/$conversationId'
    | '/api/public/mcp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/health-chat'
    | '/api/kakao-alert'
    | '/api/speech'
    | '/api/transcribe'
    | '/c/$conversationId'
    | '/api/public/mcp'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/api/health-chat'
    | '/api/kakao-alert'
    | '/api/speech'
    | '/api/transcribe'
    | '/_authenticated/c/$conversationId'
    | '/api/public/mcp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiHealthChatRoute: typeof ApiHealthChatRoute
  ApiKakaoAlertRoute: typeof ApiKakaoAlertRoute
  ApiSpeechRoute: typeof ApiSpeechRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiPublicMcpRoute: typeof ApiPublicMcpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health-chat': {
      id: '/api/health-chat'
      path: '/api/health-chat'
      fullPath: '/api/health-chat'
      preLoaderRoute: typeof ApiHealthChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kakao-alert': {
      id: '/api/kakao-alert'
      path: '/api/kakao-alert'
      fullPath: '/api/kakao-alert'
      preLoaderRoute: typeof ApiKakaoAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/speech': {
      id: '/api/speech'
      path: '/api/speech'
      fullPath: '/api/speech'
      preLoaderRoute: typeof ApiSpeechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/c/$conversationId': {
      id: '/_authenticated/c/$conversationId'
      path: '/c/$conversationId'
      fullPath: '/c/$conversationId'
      preLoaderRoute: typeof AuthenticatedCConversationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/mcp': {
      id: '/api/public/mcp'
      path: '/api/public/mcp'
      fullPath: '/api/public/mcp'
      preLoaderRoute: typeof ApiPublicMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCConversationIdRoute: typeof AuthenticatedCConversationIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCConversationIdRoute: AuthenticatedCConversationIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiHealthChatRoute: ApiHealthChatRoute,
  ApiKakaoAlertRoute: ApiKakaoAlertRoute,
  ApiSpeechRoute: ApiSpeechRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiPublicMcpRoute: ApiPublicMcpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
